services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      DATABASE_URL: file:/app/data/prod.db
      OPEN_REGISTRATION: "false"   # set to "true" to allow anyone to register
      SEED_TEST_DATA: "true"
      CLOUDFLARE_WORKER_EMAIL_URL: ""
      CLOUDFLARE_WORKER_API_SECRET: ""


    volumes:
      - ./data:/app/data
    restart: unless-stopped
