import type * as React from "react";
import type { EmailTheme } from "@/lib/email-theme";
import { substitutePlaceholders } from "./render";
import { DEFAULT_TOGGLES, type TemplateToggleKey, type TemplateToggles } from "./types";
import { InviteEmail } from "./templates/InviteEmail";
import { RsvpConfirmationEmail } from "./templates/RsvpConfirmationEmail";
import { ApprovalEmail } from "./templates/ApprovalEmail";
import { BlastEmail } from "./templates/BlastEmail";
import { HostRsvpAlertEmail } from "./templates/HostRsvpAlertEmail";
import { MagicLinkEmail } from "./templates/MagicLinkEmail";
import { WelcomeEmail } from "./templates/WelcomeEmail";
import { TestEmail } from "./templates/TestEmail";

export type TemplateId =
  | "invite"
  | "rsvpConfirmation"
  | "approval"
  | "blast"
  | "hostRsvpAlert"
  | "magicLink"
  | "welcome"
  | "test";

export const TEMPLATE_IDS: TemplateId[] = [
  "invite",
  "rsvpConfirmation",
  "approval",
  "blast",
  "hostRsvpAlert",
  "magicLink",
  "welcome",
  "test",
];

export interface EmailTemplateMeta {
  id: TemplateId;
  label: string;
  description: string;
  /** Event-scoped templates render with the event's theme; others use the app brand. */
  eventScoped: boolean;
  defaultSubject: string;
  /** Default editable body copy; empty string when the body is not editable. */
  defaultBody: string;
  bodyEditable: boolean;
  /** Placeholder names usable in subject/body copy, e.g. {guestName}. */
  placeholders: string[];
  /** Which structural toggles apply to this template. */
  toggles: TemplateToggleKey[];
}

export const EMAIL_TEMPLATE_META: Record<TemplateId, EmailTemplateMeta> = {
  invite: {
    id: "invite",
    label: "Event invite",
    description: "Sent when a host invites a guest to an event.",
    eventScoped: true,
    defaultSubject: "You're invited: {eventTitle}",
    defaultBody: "Hey {guestName},\n{hostName} has invited you to {eventTitle}. Will you be there?",
    bodyEditable: true,
    placeholders: ["guestName", "hostName", "eventTitle", "eventDate", "location"],
    toggles: ["showCoverImage", "showHostFlourish", "showMapLink", "showCalendarLinks"],
  },
  rsvpConfirmation: {
    id: "rsvpConfirmation",
    label: "RSVP confirmation",
    description: "Sent to a guest right after they RSVP.",
    eventScoped: true,
    defaultSubject: "RSVP confirmed: {eventTitle}",
    defaultBody: "Thanks {guestName} — your RSVP for {eventTitle} is in. Here are the details.",
    bodyEditable: true,
    placeholders: ["guestName", "eventTitle", "eventDate", "location", "status"],
    toggles: ["showCoverImage", "showMapLink", "showCalendarLinks"],
  },
  approval: {
    id: "approval",
    label: "RSVP approval / decline",
    description: "Sent when a host approves or declines a pending RSVP.",
    eventScoped: true,
    defaultSubject: "RSVP {decision}: {eventTitle}",
    defaultBody: "",
    bodyEditable: false,
    placeholders: ["guestName", "eventTitle", "decision"],
    toggles: ["showCoverImage"],
  },
  blast: {
    id: "blast",
    label: "Host update / reminder",
    description:
      "Host update blasts and automated event reminders. The message body is written by the host (or generated by the reminder), so only the subject is editable.",
    eventScoped: true,
    defaultSubject: "Update from {hostName}: {eventTitle}",
    defaultBody: "",
    bodyEditable: false,
    placeholders: ["hostName", "eventTitle"],
    toggles: ["showCoverImage", "showHostFlourish"],
  },
  hostRsvpAlert: {
    id: "hostRsvpAlert",
    label: "Host RSVP alert",
    description: "Notifies the host when a guest RSVPs.",
    eventScoped: true,
    defaultSubject: "New RSVP: {guestName} is {status} — {eventTitle}",
    defaultBody: "",
    bodyEditable: false,
    placeholders: ["guestName", "status", "eventTitle"],
    toggles: [],
  },
  magicLink: {
    id: "magicLink",
    label: "Sign-in link",
    description: "Passwordless sign-in email.",
    eventScoped: false,
    defaultSubject: "Your sign-in link for RSVP to Me",
    defaultBody: "Click the button below to sign in. This link expires in 15 minutes.",
    bodyEditable: true,
    placeholders: [],
    toggles: [],
  },
  welcome: {
    id: "welcome",
    label: "Account welcome",
    description: "Sent when an admin creates an account for someone.",
    eventScoped: false,
    defaultSubject: "Your account on RSVP to Me",
    defaultBody:
      "An account has been created for you. Click below to sign in — this link expires in 48 hours.",
    bodyEditable: true,
    placeholders: [],
    toggles: [],
  },
  test: {
    id: "test",
    label: "Test email",
    description: "Sent from the admin panel to verify the email configuration.",
    eventScoped: false,
    defaultSubject: "Test Email from RSVP to Me",
    defaultBody:
      "This is a test email from RSVP to Me. If you're reading this, your email configuration works!",
    bodyEditable: true,
    placeholders: [],
    toggles: [],
  },
};

// ── Sample data for previews, admin test-sends, and tests ────────────────────

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

export function sampleEventDetails() {
  return {
    id: "sample-event-id",
    slug: "sample-event",
    title: "Backyard Wine Night",
    description: "Bring a bottle and a story.",
    startAt: new Date("2026-08-21T23:00:00Z"),
    endAt: new Date("2026-08-22T02:00:00Z"),
    timezone: "America/New_York",
    locationType: "PHYSICAL" as const,
    locationName: "The Cole Residence",
    locationAddress: "123 Garden Lane, Brooklyn, NY",
    virtualUrl: null,
  };
}

export const SAMPLE_VARS: Record<TemplateId, Record<string, string>> = {
  invite: {
    guestName: "Alex Sample",
    hostName: "Joe",
    eventTitle: "Backyard Wine Night",
    eventDate: "Friday, August 21, 2026",
    location: "The Cole Residence",
  },
  rsvpConfirmation: {
    guestName: "Alex Sample",
    eventTitle: "Backyard Wine Night",
    eventDate: "Friday, August 21, 2026",
    location: "The Cole Residence",
    status: "Going",
  },
  approval: { guestName: "Alex Sample", eventTitle: "Backyard Wine Night", decision: "Approved" },
  blast: { hostName: "Joe", eventTitle: "Backyard Wine Night" },
  hostRsvpAlert: { guestName: "Alex Sample", status: "Going", eventTitle: "Backyard Wine Night" },
  magicLink: {},
  welcome: {},
  test: {},
};

export type TemplateOverrides = {
  subject?: string;
  body?: string;
} & Partial<TemplateToggles>;

export function mergedToggles(
  id: TemplateId,
  overrides?: Partial<TemplateToggles>
): TemplateToggles {
  const applicable = new Set(EMAIL_TEMPLATE_META[id].toggles);
  const result = { ...DEFAULT_TOGGLES };
  for (const key of Object.keys(result) as TemplateToggleKey[]) {
    if (applicable.has(key) && overrides?.[key] !== undefined) {
      result[key] = overrides[key]!;
    }
  }
  return result;
}

/**
 * Build a fully-rendered sample of a template (subject + element) using sample
 * data — used by the admin live preview, admin test-sends, and tests.
 * `overrides` are the (possibly unsaved) admin copy/toggle settings.
 */
export function buildSampleEmail(
  id: TemplateId,
  theme: EmailTheme,
  overrides?: TemplateOverrides
): { subject: string; element: React.ReactElement } {
  const meta = EMAIL_TEMPLATE_META[id];
  const vars = SAMPLE_VARS[id];
  const subject = substitutePlaceholders(overrides?.subject || meta.defaultSubject, vars);
  const body = substitutePlaceholders(
    (meta.bodyEditable && overrides?.body) || meta.defaultBody,
    vars
  );
  const toggles = mergedToggles(id, overrides);
  const event = sampleEventDetails();
  const eventUrl = `${APP_URL}/e/${event.slug}`;

  switch (id) {
    case "invite":
      return {
        subject,
        element: (
          <InviteEmail
            theme={theme}
            body={body}
            toggles={toggles}
            event={event}
            hostName="Joe"
            rsvpBaseUrl={`${eventUrl}/rsvp?invite=sample`}
            maybeEnabled
            eventUrl={eventUrl}
          />
        ),
      };
    case "rsvpConfirmation":
      return {
        subject,
        element: (
          <RsvpConfirmationEmail
            theme={theme}
            body={body}
            toggles={toggles}
            event={event}
            statusLabel="Going"
            eventUrl={eventUrl}
            editUrl={`${eventUrl}/rsvp?token=sample-token`}
          />
        ),
      };
    case "approval":
      return {
        subject,
        element: (
          <ApprovalEmail
            theme={theme}
            toggles={toggles}
            eventTitle={event.title}
            approved
            hostMessage="Can't wait to see you there!"
            eventUrl={eventUrl}
          />
        ),
      };
    case "blast":
      return {
        subject,
        element: (
          <BlastEmail
            theme={theme}
            toggles={toggles}
            eventTitle={event.title}
            hostName="Joe"
            message={"Quick update — we moved the start time to 7pm.\nSee you soon!"}
            eventUrl={eventUrl}
          />
        ),
      };
    case "hostRsvpAlert":
      return {
        subject,
        element: (
          <HostRsvpAlertEmail
            theme={theme}
            guestName="Alex Sample"
            statusLabel="Going"
            plusOneCount={1}
            note="So excited!"
            eventTitle={event.title}
            goingCount={12}
            maybeCount={3}
            noCount={2}
            guestListUrl={`${eventUrl}#guests`}
          />
        ),
      };
    case "magicLink":
      return {
        subject,
        element: (
          <MagicLinkEmail
            theme={theme}
            body={body}
            magicLink={`${APP_URL}/auth/verify?token=sample-token`}
          />
        ),
      };
    case "welcome":
      return {
        subject,
        element: (
          <WelcomeEmail
            theme={theme}
            body={body}
            magicLink={`${APP_URL}/auth/verify?token=sample-token`}
          />
        ),
      };
    case "test":
      return { subject, element: <TestEmail theme={theme} body={body} /> };
  }
}
